<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://android.googleapis.com/gcm/send");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"registration_ids\":[\"f8T8j2Dfjjc:APA91bF0W5o4xZ2cLnUyr780DTgqJOG2b-wtEfvq9Yh_R5l0IAS7qHBssIUvIzynwtL4Ah6sslBo27fdBcEGyyildN9LQ_ppwR5JDmpARsYwlix4upKtgeY6QecBRhIAZJvBL8He0A7p\"]}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Authorization: key=AAAAwYiMqh8:APA91bG-BXvuOa76zdECu0uAfURKgjGj43l9z_quFS40wxBSY34SEdNbyGNf6Ys4-qPeYToVBu2oUpU7zxMHA2J9W0W10zpLhWv0Rex_LXSpireNpelBzD5jMKvgfNcu0Ogtqk4_cYiA";
$headers[] = "Content-Type: \"application/json\"";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

?>